name: 'PR Opened Workflow'

on:
  pull_request:
    types: [opened, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label PR based on branch name
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  validate-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Level 1 Template Marker
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'level-1')
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Validating Level 1 PR Template..."
          if ! echo "$PR_BODY" | grep -q "## Level 1 PR Template"; then
            echo "Error: PR body is missing '## Level 1 PR Template' marker."
            echo "Please use the Level 1 PR template."
            exit 1
          fi
          echo "Level 1 Template validation passed."

      - name: Check for Level 2 Template Marker
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'level-2')
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Validating Level 2 PR Template..."
          if ! echo "$PR_BODY" | grep -q "## Level 2 PR Template"; then
            echo "Error: PR body is missing '## Level 2 PR Template' marker."
            echo "Please use the Level 2 PR template."
            exit 1
          fi
          echo "Level 2 Template validation passed."

      - name: Check for Level 3 Template Markers and Fields
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'level-3')
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Validating Level 3 PR Template..."
          if ! echo "$PR_BODY" | grep -q "## Level 3 PR Template"; then
            echo "Error: PR body is missing '## Level 3 PR Template' marker."
            echo "Please use the Level 3 PR template and fill out the metadata section."
            exit 1
          fi
          project_name=$(echo "$PR_BODY" | grep 'PROJECT_NAME:' | cut -d ':' -f2- | xargs)
          if [ -z "$project_name" ]; then
            echo "Error: 'PROJECT_NAME:' is empty in the template."
            echo "Please fill out all required fields in the metadata block."
            exit 1
          fi
          echo "Level 3 Template validation passed."

      - name: Check for Level 4 Template Markers and Fields
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'level-4')
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Validating Level 4 PR Template..."
          if ! echo "$PR_BODY" | grep -q "## Level 4 PR Template"; then
            echo "Error: PR body is missing '## Level 4 PR Template' marker."
            echo "Please use the Level 4 PR template."
            exit 1
          fi
          team_name=$(echo "$PR_BODY" | grep 'TEAM_NAME:' | cut -d ':' -f2- | xargs)
          if [ -z "$team_name" ]; then
            echo "Error: 'TEAM_NAME:' is empty in the template."
            echo "Please fill out all required fields."
            exit 1
          fi
          echo "Level 4 Template validation passed."
